[package]
name = "dungeon-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
config = "0.14"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
rand = "0.8"
rand_chacha = "0.3"
printpdf = "0.7"
anyhow = "1"
thiserror = "1"
walkdir = "2"

[dev-dependencies]
pretty_assertions = "1"
